spring:
  application:
    name: discovery-service
  # cloud:
  #   config:
  #     uri: http://localhost:8888
  #     name: discovery-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0


