spring:
  application:
    name: patient-service



h2:
  console:
    enabled: true
    path: /h2


server:
  port: 8080


logging:
  file:
    name: logs/dev.log
  level:
    com:
      ust:
        jpa_demo: DEBUG
    web: warn
  pattern:
    file: "%d(HH:mm:ss.SSS} {%t %-5level %logger{36} - %msg%n"
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{project}] [%thread] %-5level %logger{36} - %msg%n'

  logback:
    rollingpolicy:
      max-file-size: 1MB

  debug: true